const CATEGORIES = {
	ENTERTAINMENT: {
		BOOKS: 10,
		FILM: 11,
		MUSIC: 12,
		MUSICALS__THEATRES: 13,
		TELEVISION: 14,
		VIDEO_GAMES: 15,
		BOARD_GAMES: 16,
		COMICS: 29,
		JAPANESE_ANIME__MANGA: 31,
		CARTOON__ANIMATIONS: 32,
	},
	SCIENCE: {
		COMPUTERS: 18,
		MATHEMATICS: 19,
		GADGETS: 30,
	},
	GENERAL_KNOWLEDGE: 9,
	SCIENCE__NATURE: 17,
	MYTHOLOGY: 20,
	SPORTS: 21,
	GEOGRAPHY: 22,
	HISTORY: 23,
	POLITICS: 24,
	ART: 25,
	CELEBRITIES: 26,
	ANIMALS: 27,
	VEHICLES: 28,
}
const TYPES = {
	MULTIPLE: 'multiple',
	TRUE_FALSE: 'boolean',
}
const DIFFICULTIES = {
	EASY: 'easy',
	MEDIUM: 'medium',
	HARD: 'hard',
}

export const QUESTION_NUM = 10
export const QUESTION_CATEGORY = CATEGORIES.ENTERTAINMENT.VIDEO_GAMES
export const QUESTION_DIFFICULTY = null
export const QUESTION_TYPE = TYPES.MULTIPLE
export const SCORE_TO_WIN = 7
